name: docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: sudo apt-get install -y doxygen python3-pip npm g++ libpcap-dev texlive-font-utils
      - run: python3 -m pip install meson ninja
      - run: python3 -m pip install -r docs/requirements.txt
      - run: sudo npm install -g teroshdl
      - run: meson setup build
      - run: meson compile docs -v -C build
      - run: mkdocs gh-deploy --force
